{
 "title": "Azure App Service",
 "description": "Azure Monitor for Hadoop & Data Lake",
 "time": { "from": "now-3h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "Subscription",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "ResourceGroup", "label": "Resource Group", "query": "ResourceGroups()" },
   {
    "name": "ResourceName",
    "label": "Resource Name",
    "query": "ResourceNames($ResourceGroup,Microsoft.Web/sites)"
   },
   {
    "name": "AppServiceSlot",
    "label": "Slots",
    "query": "ResourceNames($ResourceGroup,Microsoft.Web/sites/slots)"
   },
   {
    "name": "Plan",
    "query": "ResourceNames($ResourceGroup,Microsoft.Web/serverFarms)"
   }
  ]
 },
 "panels": [
  { "title": "$ResourceName - PRD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total HTTP 200 Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Total HTTP 200 Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http2xx",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:98", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:99", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:100", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:101", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:102", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:103", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:104", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:105", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:106", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Total HTTP 3xx Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Total HTTP 200 Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http3xx",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3061", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3062", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3063", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3064", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3065", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3066", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3067", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3068", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3069", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Total HTTP 4xx Messages",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Total HTTP 200 Messages",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http4xx",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:3122", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:3123", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:3124", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:3125", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:3126", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:3127", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:3128", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:3129", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:3130", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Data In (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Data In / Hour",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "BytesReceived",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1H",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Data Out (Last Hour)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Data In / Hour",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "BytesSent",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1H",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Execution Thread Count ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Total amount of data written to the account ( last 5 mins )",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Threads",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "HTTP Server Errors - Last Hour",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "HTTP Server Errors - Last Hour",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Http5xx",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1H",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Requests in App Queue",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "Requests in App Queue",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "RequestsInApplicationQueue",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Count",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "AppConnections",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:91", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:92", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:93", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:94", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:95", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:96", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:97", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:98", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:99", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Memory - Working Set",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Total",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "MemoryWorkingSet",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1H",
      "timeGrains": [
       { "$$hashKey": "object:35", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:36", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:37", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:38", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:39", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:40", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:41", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:42", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:43", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "HttpResponseTime",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Requests / min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Count",
      "alias": "Requests / min",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "Requests",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1M",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Average Memory - Working Set",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Average Memory - Working Set",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "AverageMemoryWorkingSet",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Data Read / min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Data Read / min",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "IoReadBytesPerSecond",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Data Write / min",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "alias": "Data Write / min",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/sites",
      "metricName": "IoWriteOperationsPerSecond",
      "metricNamespace": "Microsoft.Web/sites",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "App Service - Slot $AppServiceSlot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "AppServiceSlot",
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time - Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Response Time",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "HttpResponseTime",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:2549", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:2550", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:2551", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:2552", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:2553", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:2554", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:2555", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:2556", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:2557", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "Requests",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Requests",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Memory - Working Set",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Memory - Working Set",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "MemoryWorkingSet",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:36", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:37", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:38", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:39", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:40", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:41", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:42", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:43", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:44", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 2xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 2xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http2xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:112", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:113", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:114", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:115", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:116", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:117", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:118", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:119", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:120", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 3xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 3xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http3xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:48", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:49", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:50", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:51", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:52", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:53", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:54", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:55", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:56", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 4xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 4xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http4xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:83", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:84", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:85", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:86", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:87", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:88", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:89", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:90", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:91", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Requests / min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Requests / min",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Requests",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:87", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:88", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:89", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:90", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:91", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:92", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:93", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:94", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:95", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    }
   ]
  },
  {
   "title": "App Service - Slot $AppServiceSlot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time - Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Response Time",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "HttpResponseTime",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:2549", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:2550", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:2551", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:2552", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:2553", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:2554", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:2555", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:2556", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:2557", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "Requests",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Requests",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Memory - Working Set",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Memory - Working Set",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "MemoryWorkingSet",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:36", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:37", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:38", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:39", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:40", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:41", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:42", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:43", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:44", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 2xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 2xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http2xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:112", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:113", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:114", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:115", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:116", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:117", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:118", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:119", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:120", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 3xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 3xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http3xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:48", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:49", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:50", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:51", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:52", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:53", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:54", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:55", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:56", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 4xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 4xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http4xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:83", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:84", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:85", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:86", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:87", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:88", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:89", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:90", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:91", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Requests / min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Requests / min",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Requests",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:87", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:88", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:89", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:90", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:91", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:92", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:93", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:94", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:95", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    }
   ]
  },
  {
   "title": "App Service - Slot $AppServiceSlot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time - Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Response Time",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "HttpResponseTime",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:2549", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:2550", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:2551", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:2552", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:2553", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:2554", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:2555", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:2556", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:2557", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "Requests",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Requests",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Memory - Working Set",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Memory - Working Set",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "MemoryWorkingSet",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:36", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:37", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:38", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:39", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:40", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:41", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:42", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:43", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:44", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 2xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 2xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http2xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:112", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:113", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:114", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:115", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:116", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:117", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:118", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:119", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:120", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 3xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 3xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http3xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:48", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:49", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:50", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:51", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:52", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:53", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:54", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:55", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:56", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 4xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 4xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http4xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:83", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:84", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:85", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:86", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:87", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:88", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:89", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:90", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:91", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Requests / min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Requests / min",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Requests",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:87", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:88", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:89", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:90", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:91", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:92", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:93", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:94", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:95", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    }
   ]
  },
  {
   "title": "App Service - Slot $AppServiceSlot",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time - Mean",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Response Time",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "HttpResponseTime",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:2549", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:2550", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:2551", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:2552", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:2553", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:2554", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:2555", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:2556", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:2557", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "Requests",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Requests",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Memory - Working Set",
     "type": "stat",
     "gridPos": { "h": 4, "w": 7, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Memory - Working Set",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "MemoryWorkingSet",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:36", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:37", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:38", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:39", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:40", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:41", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:42", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:43", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:44", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 2xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 15, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 2xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http2xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:112", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:113", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:114", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:115", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:116", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:117", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:118", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:119", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:120", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 3xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 18, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 3xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http3xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:48", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:49", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:50", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:51", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:52", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:53", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:54", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:55", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:56", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "HTTP 4xx - Count",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 21, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "sum" ] } },
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "HTTP 4xx - Count",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Http4xx",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:83", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:84", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:85", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:86", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:87", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:88", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:89", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:90", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:91", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    },
    {
     "title": "Requests / min",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "dimension": [ "none" ],
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeColumn": "timestamp",
        "timeGrain": "auto",
        "timeGrainType": "auto",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series",
        "workspace": "f08dd684-9831-43db-b782-482cbff7a88c"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "Requests / min",
        "allowedTimeGrainsMs": [
         60000,
         300000,
         900000,
         1800000,
         3600000,
         21600000,
         43200000,
         86400000
        ],
        "dimension": "",
        "dimensionFilter": "*",
        "dimensionFilters": [],
        "dimensions": [
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites/slots",
        "metricName": "Requests",
        "metricNamespace": "Microsoft.Web/sites/slots",
        "resourceGroup": "$ResourceGroup",
        "resourceName": "$AppServiceSlot",
        "timeGrain": "auto",
        "timeGrains": [
         { "$$hashKey": "object:87", "text": "auto", "value": "auto" },
         { "$$hashKey": "object:88", "text": "1 minute", "value": "PT1M" },
         { "$$hashKey": "object:89", "text": "5 minutes", "value": "PT5M" },
         { "$$hashKey": "object:90", "text": "15 minutes", "value": "PT15M" },
         { "$$hashKey": "object:91", "text": "30 minutes", "value": "PT30M" },
         { "$$hashKey": "object:92", "text": "1 hour", "value": "PT1H" },
         { "$$hashKey": "object:93", "text": "6 hours", "value": "PT6H" },
         { "$$hashKey": "object:94", "text": "12 hours", "value": "PT12H" },
         { "$$hashKey": "object:95", "text": "1 day", "value": "P1D" }
        ],
        "top": "10"
       },
       "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
       "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
      }
     ]
    }
   ]
  },
  { "title": "Farm - $Plan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "Plan" },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "CpuPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1763", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1764", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1765", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1766", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1767", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1768", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1769", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1770", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1771", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "CpuPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1763", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1764", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1765", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1766", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1767", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1768", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1769", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1770", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1771", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "MemoryPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1789", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1790", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1791", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1792", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1793", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1794", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1795", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1796", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1797", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "MemoryPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1789", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1790", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1791", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1792", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1793", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1794", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1795", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1796", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1797", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Disk Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "DiskQueueLength",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1837", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1838", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1839", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1840", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1841", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1842", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1843", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1844", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1845", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "HTTP Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "HttpQueueLength",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1911", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1912", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1913", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1914", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1915", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1916", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1917", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1918", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1919", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  { "title": "Farm - $Plan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "CPU %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "CpuPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1763", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1764", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1765", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1766", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1767", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1768", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1769", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1770", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1771", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "CPU %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "CpuPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1763", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1764", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1765", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1766", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1767", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1768", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1769", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1770", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1771", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "MemoryPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1789", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1790", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1791", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1792", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1793", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1794", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1795", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1796", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1797", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Memory %",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "MemoryPercentage",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1789", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1790", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1791", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1792", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1793", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1794", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1795", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1796", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1797", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Disk Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "DiskQueueLength",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1837", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1838", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1839", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1840", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1841", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1842", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1843", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1844", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1845", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "HTTP Queue",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": [],
      "metricName": "select",
      "timeGrain": "auto"
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "None",
       "Average",
       "Minimum",
       "Maximum",
       "Total",
       "Count"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [
       { "text": "Instance", "value": "Instance" }
      ],
      "metricDefinition": "Microsoft.Web/serverFarms",
      "metricName": "HttpQueueLength",
      "metricNamespace": "Microsoft.Web/serverFarms",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$Plan",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:1911", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:1912", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:1913", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:1914", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:1915", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:1916", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:1917", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:1918", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:1919", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  }
 ]
}