{
 "title": "Azure Storage Account",
 "tags": [
  "InfraOPS",
  "Storage",
  "Azure"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Subscriptions",
    "label": "Subscriptions",
    "query": "grafana-azure-monitor-datasource"
   },
   { "name": "ResourceGroup", "label": "Resource Group", "query": "ResourceGroups()" },
   { "name": "Namespaces", "label": "Namespaces", "query": "Namespaces($ResourceGroup)" },
   {
    "name": "ResourceName",
    "label": "ResourceName",
    "query": "ResourceNames($ResourceGroup,$Namespaces)"
   }
  ]
 },
 "panels": [
  {
   "title": "Microsoft Azure Storage Account",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": {
    "content": "![Veeam Backup for Microsoft Office 365 - Dashboard](https://www.jorgedelacruz.es/wp-content/uploads/2019/03/microsoft-azure-500x500.png)\n\n\n"
   }
  },
  {
   "title": "Availability",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "Availability",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Used Capacity",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Total"
      ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       3600000
      ],
      "dimension": "",
      "dimensionFilter": "*",
      "dimensionFilters": [],
      "dimensions": [],
      "metricDefinition": "$Namespaces",
      "metricName": "UsedCapacity",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "PT1H",
      "timeGrains": [
       { "$$hashKey": "object:309", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:310", "text": "1 hour", "value": "PT1H" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "Ingress",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Egress",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "Egress",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "PutBlob",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "appInsights": {
      "dimension": [ "none" ],
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimensionFilters": [
       { "dimension": "ApiName", "filter": "PutBlob", "operator": "eq" }
      ],
      "dimensions": [
       { "$$hashKey": "object:416", "text": "None", "value": "None" },
       { "$$hashKey": "object:417", "text": "Response type", "value": "ResponseType" },
       { "$$hashKey": "object:418", "text": "Geo type", "value": "GeoType" },
       { "$$hashKey": "object:419", "text": "API name", "value": "ApiName" },
       { "$$hashKey": "object:420", "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "Transactions",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:405", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:406", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:407", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:408", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:409", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:410", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:411", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:412", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:413", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "insightsAnalytics": { "query": "", "resultFormat": "time_series" },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "PutBlock",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "dimension": "ApiName",
      "dimensionFilter": "PutBlock",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "Transactions",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "PutBlockList",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "dimension": "ApiName",
      "dimensionFilter": "PutBlockList",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "Transactions",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "EntityGroupTransaction",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "dimension": "ApiName",
      "dimensionFilter": "EntityGroupTransaction",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "Transactions",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "QueryEntities",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [ "Total" ],
      "aggregation": "Total",
      "dimension": "ApiName",
      "dimensionFilter": "QueryEntities",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Response type", "value": "ResponseType" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "Transactions",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  },
  {
   "title": "Ingress and Egress Traffic per API name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes", "label": "Ingress" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "alias": "{{dimensionvalue}}.ingress",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "ApiName",
      "dimensionFilter": "*",
      "dimensions": [
       { "$$hashKey": "object:243", "text": "None", "value": "None" },
       { "$$hashKey": "object:244", "text": "Geo type", "value": "GeoType" },
       { "$$hashKey": "object:245", "text": "API name", "value": "ApiName" },
       { "$$hashKey": "object:246", "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "Ingress",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:234", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:235", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:236", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:237", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:238", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:239", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:240", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:241", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:242", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    },
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "timeGrainType": "auto",
      "valueColumn": "",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "c7ead545-8434-489e-a604-caa58d4a9cac"
     },
     "azureMonitor": {
      "aggOptions": [
       "Total",
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Total",
      "alias": "{{dimensionvalue}}.egress",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "ApiName",
      "dimensionFilter": "*",
      "dimensions": [
       { "$$hashKey": "object:264", "text": "None", "value": "None" },
       { "$$hashKey": "object:265", "text": "Geo type", "value": "GeoType" },
       { "$$hashKey": "object:266", "text": "API name", "value": "ApiName" },
       { "$$hashKey": "object:267", "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "Egress",
      "metricNamespace": "$Namespaces",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:255", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:256", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:257", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:258", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:259", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:260", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:261", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:262", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:263", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "ea75cb51-afe3-4691-9136-eb174ad5a756"
    }
   ]
  },
  {
   "title": "Success Server Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms", "label": "Success Server Latency (Avg)" }
   ],
   "targets": [
    {
     "appInsights": {
      "groupBy": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "spliton": "",
      "timeGrainType": "auto",
      "xaxis": "timestamp",
      "yaxis": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Minimum",
       "Maximum"
      ],
      "aggregation": "Average",
      "alias": "{{dimensionvalue}}",
      "dimension": "ApiName",
      "dimensionFilter": "*",
      "dimensions": [
       { "text": "None", "value": "None" },
       { "text": "Geo type", "value": "GeoType" },
       { "text": "API name", "value": "ApiName" },
       { "text": "Authentication", "value": "Authentication" }
      ],
      "metricDefinition": "$Namespaces",
      "metricName": "SuccessServerLatency",
      "resourceGroup": "$ResourceGroup",
      "resourceName": "$ResourceName",
      "timeGrain": "auto",
      "timeGrains": [
       { "text": "auto", "value": "auto" },
       { "text": "1 minute", "value": "PT1M" },
       { "text": "5 minutes", "value": "PT5M" },
       { "text": "15 minutes", "value": "PT15M" },
       { "text": "30 minutes", "value": "PT30M" },
       { "text": "1 hour", "value": "PT1H" },
       { "text": "6 hours", "value": "PT6H" },
       { "text": "12 hours", "value": "PT12H" },
       { "text": "1 day", "value": "P1D" }
      ]
     }
    }
   ]
  }
 ]
}