{
 "title": "Oracle - Exadata Cell Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Ambiente", "query": "label_values(job)" },
   {
    "name": "exa",
    "query": "label_values({job=~\"$job\"},instance)"
   },
   {
    "name": "db",
    "query": "label_values({job=~\"$job\"},instance)"
   },
   {
    "name": "db_name",
    "label": "Bancos",
    "query": "query_result(sort_desc(topk(12,sum by(object_name)(rate(ExadataDBIO{job=\"$job\",instance=\"$db\",metric_name=\"DB_FD_IO_LOAD\"}[30m]))/3)))"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ExadataCELLMetrics{job=\"$job\",instance=\"$exa\",metric_name=\"CL_CPUT\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ExadataCELLMetrics{job=\"$job\",instance=\"$exa\",metric_name=\"CL_MEMUT\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ExadataCELLMetrics{job=\"$job\",instance=\"$exa\",metric_name=\"CL_TEMP\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "DB Node Network send/receive rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "ExadataDBNodeMetrics{job=\"$job\",instance=\"$exa\",metric_name=\"N_HCA_MB_RCV_SEC\"}/8",
     "legendFormat": "the number of megabytes received per second from  {{node}}"
    },
    {
     "expr": "ExadataDBNodeMetrics{job=\"$job\",instance=\"$exa\",metric_name=\"N_HCA_MB_TRANS_SEC\"}/8",
     "legendFormat": "the number of megabytes received per second from {{node}}"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 19 },
   "repeat": "db_name",
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  },
  {
   "title": "$db_name",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_FD_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "FLASH IO"
    },
    {
     "expr": "sum(ExadataDBIO{job=\"$job\",metric_name=\"DB_IO_LOAD\", object_name=\"$db_name\"})/3",
     "legendFormat": "HDD IO"
    }
   ]
  }
 ]
}