{
 "title": "DBA - Exadata DB Machine",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   { "name": "job", "label": "Ambiente", "query": { "query": "label_values(job)" } },
   {
    "name": "db",
    "query": {
     "query": "label_values({job=~\"$job\"},instance)"
    }
   },
   {
    "name": "node1",
    "query": {
     "query": "label_values({job=~\"$job\"},instance)"
    }
   },
   {
    "name": "node2",
    "query": {
     "query": "label_values({job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ExadataCELLMetrics{job=\"$job\",instance=\"$db\",metric_name=\"CL_CPUT\"}",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "ExadataDBNodeMetrics{job=\"$job\",instance=\"$db\",metric_name=\"DS_CPUT\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "RAM - DB Node 01",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node1\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node1\",job=~\"$job\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "RAM - DB Node 02",
   "type": "gauge",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=~\"$node2\",job=~\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=~\"$node2\",job=~\"$job\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "The percentage of total space utilized on the file system",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(8, sum by (node,metric,object_name) (ExadataDBNodeMetrics{job=\"$job\",instance=\"$db\",metric_name=\"DS_FSUT\"}))",
     "legendFormat": "\"{{object_name}}\" in {{node}}"
    }
   ]
  },
  {
   "title": "Cell Memory Utilization",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ExadataCELLMetrics{job=\"$job\",instance=\"$db\",metric_name=\"CL_MEMUT\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ExadataCELLMetrics{job=\"$job\",instance=\"$db\",metric_name=\"CL_TEMP\"}",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "ExadataDBNodeMetrics{job=\"$job\",instance=\"$db\",metric_name=\"DS_TEMP\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "DB Node Network send/receive rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "expr": "topk(5, sum by (device,intance) (rate(node_network_receive_bytes_total{job=\"$job\",instance=\"$node1\"}[5m])))/125000",
     "legendFormat": "node1 : {{device}} - Receive"
    },
    {
     "expr": "topk(5, sum by (device,intance) (rate(node_network_transmit_bytes_total{job=\"$job\",instance=\"$node1\"}[5m])))/125000",
     "legendFormat": "node1 : {{device}} - Transmit"
    },
    {
     "expr": "topk(5, sum by (device,intance) (rate(node_network_receive_bytes_total{job=\"$job\",instance=\"$node2\"}[5m])))/125000",
     "legendFormat": "node2 : {{device}} - Receive"
    },
    {
     "expr": "topk(5, sum by (device,intance) (rate(node_network_transmit_bytes_total{job=\"$job\",instance=\"$node2\"}[5m])))/125000",
     "legendFormat": "node2 : {{device}} - Transmit"
    }
   ]
  }
 ]
}