{
 "title": "DBA - Sesssions Oracle QA",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "DB",
    "query": {
     "query": "label_values({job=\"ORACLEQA\"},inst)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Sessões Geral",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "OracleDBMetrics{metric_name=\"oracle-session\"} ",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  { "title": "$DB Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }, "repeat": "DB" },
  {
   "title": "SESSOES",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "OracleDBMetrics{inst=\"$DB\",metric_name=\"oracle-session\"} ",
     "legendFormat": "{{inst}}"
    }
   ]
  },
  {
   "title": "SESSOES - DETALHES",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "OracleDBMetrics{inst=\"$DB\",metric_name=\"oracle-session-detail\"}",
     "legendFormat": "{{inst}} - {{object_name}}"
    }
   ]
  }
 ]
}