{
 "title": "Canais Digitais - Cartao Drill Down",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "data",
    "query": {
     "query": "label_values(EEVC_QTD_DE_PGT, date)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Arquivos Recebidos x Enviados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Enviados x Recebidos - $data",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "repeat": "data",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "EEVC_QTD_DE_PGT{date=\"$data\"}",
     "legendFormat": "Recebidos"
    },
    {
     "expr": "EEVC_QTD_DE_ARQ_ENV{date=\"$data\"}",
     "legendFormat": "Enviados"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Unidades com registros de venda em cada arquivo e flag indicando se arquivo febraban foi enviado com sucesso para o respectivo SAN",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "last_over_time(EEVC_QTD_DE_ARQ_ENV_UNID{date=\"$data\"}[3h])"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Recebimento e leitura do extrato eletrônico da Rede",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "EEVC_QTD_DE_ARQ_ENV{}/EEVC_QTD_DE_PGT{} * 100",
       "legendFormat": "{{date}}"
      }
     ]
    },
    {
     "title": "Unidades com registros de venda em cada arquivo e flag indicando se arquivo febraban foi enviado com sucesso para o respectivo SAN",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "EEVC_QTD_DE_ARQ_ENV_UNID{date=\"$data\"}",
       "legendFormat": "{{unidade}} - {{date}} - {{extrato}} - {{file}}"
      }
     ]
    },
    {
     "title": "Envio de arquivos Febraban para baixa no SAN",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 12, "x": 10, "y": 28 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "EEVC_QTD_DE_ARQ_ENV{}", "legendFormat": "{{date}} - {{file}}" }
     ]
    },
    {
     "title": "Recebimento e leitura do extrato eletrônico da Rede",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "EEVC_QTD_DE_PGT{}", "legendFormat": "{{date}} - {{file}}" },
      { "expr": "EEVC_QTD_DE_ARQ_ENV{}", "legendFormat": "{{date}} - {{file}}" }
     ]
    }
   ]
  }
 ]
}