{
 "title": "Canais Digitais - Cartao",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   {
    "name": "data",
    "query": {
     "query": "label_values(EEVC_QTD_DE_PGT, date)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Arquivos Recebidos x Enviados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$data",
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 1 },
   "repeat": "data",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(EEVC_QTD_DE_ARQ_ENV{date=\"$data\"}+0.1)/(EEVC_QTD_DE_PGT{date=\"$data\"}+0.1) * 100",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "OPEN HIGH ALERTS",
   "type": "table-old",
   "description": "MAKE SURE TO SCROLL TO BOTTOM AND CHECK FOR MORE ALERTS",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "alertname!=\"asm_use_warn\",alertname!=\"asm_use_high\",alertname!=\"asm_use\",severity=~\"[3-4]\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Enviados x Recebidos - $data",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 22 },
   "repeat": "data",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "EEVC_QTD_DE_PGT{date=\"$data\"}",
     "legendFormat": "Recebidos"
    },
    {
     "expr": "EEVC_QTD_DE_ARQ_ENV{date=\"$data\"}",
     "legendFormat": "Enviados"
    }
   ]
  },
  {
   "title": "Unidades com registros de venda em cada arquivo e flag indicando se arquivo febraban foi enviado com sucesso para o respectivo SAN",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "EEVC_QTD_DE_ARQ_ENV_UNID{date=\"$data\"}"
    }
   ]
  },
  {
   "title": "Recebimento e leitura do extrato eletrônico da Rede",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "EEVC_QTD_DE_ARQ_ENV{}/EEVC_QTD_DE_PGT{} * 100",
     "legendFormat": "{{date}}"
    }
   ]
  },
  {
   "title": "Unidades com registros de venda em cada arquivo e flag indicando se arquivo febraban foi enviado com sucesso para o respectivo SAN",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "EEVC_QTD_DE_ARQ_ENV_UNID{date=\"$data\"}",
     "legendFormat": "{{unidade}} - {{date}} - {{extrato}} - {{file}}"
    }
   ]
  },
  {
   "title": "Envio de arquivos Febraban para baixa no SAN",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 10, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "EEVC_QTD_DE_ARQ_ENV{}", "legendFormat": "{{date}} - {{file}}" }
   ]
  },
  {
   "title": "Recebimento e leitura do extrato eletrônico da Rede",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "EEVC_QTD_DE_PGT{}", "legendFormat": "{{date}} - {{file}}" },
    { "expr": "EEVC_QTD_DE_ARQ_ENV{}", "legendFormat": "{{date}} - {{file}}" }
   ]
  }
 ]
}