{
 "title": "VM Overview - Windows Exporter - TRD",
 "description": "Basic overview of windows host metrics, based on WMI Exporter (v0.7.0)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datacenter", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(wmi_os_time, job)" } },
   {
    "name": "host",
    "label": "Hostname",
    "query": {
     "query": "label_values(wmi_os_time{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime | $host",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "repeat": "host",
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_os_time{instance=~\"$host\"} - wmi_system_system_up_time{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "repeat": "host",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_cs_logical_processors{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "repeat": "host",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - avg(irate(wmi_cpu_time_total{instance=~\"$host\",mode=\"idle\"}[5m])) > 0"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "repeat": "host",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(wmi_os_physical_memory_free_bytes{instance=~\"$host\"} / wmi_cs_physical_memory_bytes{instance=~\"$host\"}) > 0"
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "repeat": "host",
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "1 - (sum(wmi_logical_disk_free_bytes{instance=~\"$host\",volume=~\"^[A-Z]:.*$\"}) / sum(wmi_logical_disk_size_bytes{instance=~\"$host\",volume=~\"^[A-Z]:.*$\"})) > 0"
    }
   ]
  },
  {
   "title": "Net IN (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 15, "y": 1 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(wmi_net_bytes_received_total{instance=~\"$host\"}[24h]))"
    }
   ]
  },
  {
   "title": "Net OUT (24h)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "repeat": "host",
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(wmi_net_bytes_sent_total{instance=~\"$host\"}[24h]))"
    }
   ]
  },
  {
   "title": "Disk (Free)",
   "type": "table-old",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "repeat": "host",
   "targets": [
    {
     "expr": "sort_desc(wmi_logical_disk_free_bytes{instance=~\"$host\",volume=~\"(^[A-Z]:$)\"})"
    }
   ]
  }
 ]
}