{
 "title": "INFRA - AD & DNS",
 "description": "Active Directory and DNS Dashboard using Prometheus windows_Exporter ",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNS Queries",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(windows_dns_queries_total{protocol=\"udp\"}[5m]))"
    }
   ]
  },
  {
   "title": "DNS Queries/Sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(irate(windows_dns_queries_total{protocol=\"udp\"}[5m]))"
    }
   ]
  },
  {
   "title": "LDAP Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[5m]))"
    }
   ]
  },
  {
   "title": "LDAP Connections/Sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[5m]))"
    }
   ]
  },
  {
   "title": "LDAP Searches",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(delta(windows_ad_ldap_searches_total{}[5m]))"
    }
   ]
  },
  {
   "title": "LDAP Searches / Sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(windows_ad_ldap_searches_total{}[5m]))"
    }
   ]
  },
  { "title": "DNS Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "DNS Queries/Responses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_dns_queries_total{}[5m])",
     "legendFormat": "in-{{protocol}} ({{instance}})"
    },
    {
     "expr": "-delta(windows_dns_responses_total{}[5m])",
     "legendFormat": "out-{{protocol}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Recursive Queries / Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_dns_recursive_query_failures_total[5m])",
     "legendFormat": "failures ({{instance}})"
    },
    {
     "expr": "delta(windows_dns_recursive_queries_total[5m])",
     "legendFormat": "queries ({{instance}})"
    },
    {
     "expr": "delta(windows_dns_recursive_query_send_timeouts_total[5m])",
     "legendFormat": "sent timeouts ({{instance}})"
    }
   ]
  },
  { "title": "AD Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Pending Syncronisations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_ad_replication_pending_synchronizations{})"
    }
   ]
  },
  {
   "title": "Pending Operations",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(windows_ad_replication_pending_operations{})"
    }
   ]
  },
  {
   "title": "Inbound Updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_replication_inbound_objects_updated_total{}[5m])",
     "legendFormat": "objects ({{instance}})"
    },
    {
     "expr": "delta(windows_ad_replication_inbound_properties_updated_total{}[5m])",
     "legendFormat": "properties ({{instance}})"
    }
   ]
  },
  {
   "title": "Intrasite Replication Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_replication_data_intrasite_bytes_total{direction=\"inbound\"}[5m])",
     "legendFormat": "inbound ({{instance}})"
    },
    {
     "expr": "-delta(windows_ad_replication_data_intrasite_bytes_total{direction=\"outbound\"}[5m])",
     "legendFormat": "outbound ({{instance}})"
    }
   ]
  },
  {
   "title": "Intersite Replication Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "delta(windows_ad_replication_data_intersite_bytes_total{direction=\"inbound\"}[5m])",
     "legendFormat": "inbound ({{instance}})"
    },
    {
     "expr": "-delta(windows_ad_replication_data_intersite_bytes_total{direction=\"inbound\"}[5m])",
     "legendFormat": "outbound ({{instance}})"
    }
   ]
  },
  {
   "title": "AD Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "AD Operations (Detailed)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_directory_operations_total{}[5m])",
       "legendFormat": "{{origin}}-{{operation}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Directory Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_database_operations_total{}[5m])",
       "legendFormat": "{{operation}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "AD Binds",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "AD Bind",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_binds_total{}[5m])",
       "legendFormat": "{{bind_method}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "AD LDAP Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDAP Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[5m])",
       "legendFormat": "Opened ({{instance}})"
      },
      {
       "expr": "-(delta(windows_ad_ldap_closed_connections_total{}[5m]))",
       "legendFormat": "Closed ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "AD Heatmap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDAP connections HeatMap",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "delta(windows_ad_ldap_opened_connections_total{type=\"ldap\"}[5m])"
      }
     ]
    },
    {
     "title": "LDAP Searches",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "delta(windows_ad_ldap_searches_total{}[5m])"
      }
     ]
    }
   ]
  },
  {
   "title": "AD LDAP Searches/Updates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "LDAP Searches/Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_ad_ldap_writes_total{}[5m])",
       "legendFormat": "Writes ({{instance}})"
      },
      {
       "expr": "-delta(windows_ad_ldap_searches_total{}[5m])",
       "legendFormat": "Searches ({{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "DNS Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(windows_dns_memory_used_bytes_total{}[5m])",
       "legendFormat": "{{area}} ({{instance}})"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS Updates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Updates",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_dns_dynamic_updates_received_total[5m])",
       "legendFormat": "{{operation}} ({{instance}})"
      }
     ]
    },
    {
     "title": "Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "delta(windows_dns_dynamic_updates_failures_total[5m])",
       "legendFormat": "{{reason}} ({{instance}})"
      }
     ]
    }
   ]
  }
 ]
}