{
 "title": "INFRA - VMware ESX",
 "description": "ESXI Host and VM information",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Host:",
    "query": {
     "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
    }
   },
   { "name": "vms", "query": { "query": "label_values(vm_name)" } }
  ]
 },
 "panels": [
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_cpu_usage{host_name=\"$hostname\"} / vmware_host_cpu_max{host_name=\"$hostname\"} * 100",
     "legendFormat": "$hostname"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_memory_usage{host_name=\"$hostname\"} / vmware_host_memory_max{host_name=\"$hostname\"} * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_host_boot_timestamp_seconds{host_name=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Host State",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_host_power_state{host_name=\"$hostname\"}"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "vms" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  }
 ]
}