{
 "title": "Alertas - Infra Indisponibilidade",
 "description": "Dashboard to visualize only Open(LIVE) Alerts of AlertManager instead of looking in Slack, Teams, and Emails.",
 "time": { "from": "2021-09-02T14:03:16.905Z", "to": "2021-09-02T14:13:16.907Z" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "alertmanager",
    "label": "Alertmanager",
    "query": "camptocamp-prometheus-alertmanager-datasource"
   },
   { "name": "severity", "label": "Severity", "query": "label_values(severity)" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disponibilidade",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsSystem" } },
   "targets": [
    {
     "expr": "alertname=~\"service_down\"",
     "labelSelector": "*",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
     "options": {
      "content": "# <center>ALERTAS INFRA</center>"
     },
     "targets": [
      {}
     ]
    },
    {
     "title": "Disponibilidade",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "alertname=~\"service_down\"",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 6, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "alertname=~\"HostHighCpuLoad\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "MEMÓRIA",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "alertname=~\"HostOutOfMemory2\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "DISCO",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "alertname=~\"HostOutOfDiskSpace\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "severity=~\"$severity\",alertname=~\".*\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "Total Critical",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 5, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "  severity=~\"4\",alertname=~\".*\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "Total High",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "  severity=~\"3\",alertname=~\".*\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "Total Warning",
     "type": "stat",
     "gridPos": { "h": 4, "w": 3, "x": 11, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "  severity=~\"2\",alertname=~\".*\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "DB Down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "alertname=~\"oracleup\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "Service Down",
     "type": "stat",
     "gridPos": { "h": 4, "w": 5, "x": 19, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "  severity=~\"$severity\",alertname=~\"ServiceDown\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "single"
      }
     ]
    },
    {
     "title": "OPEN ALERTS Oracle",
     "type": "table-old",
     "description": "MAKE SURE TO SCROLL TO BOTTOM AND CHECK FOR MORE ALERTS",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "job=~\"ORACLE.+|x8|x5\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Web Alerts",
     "type": "table-old",
     "description": "MAKE SURE TO SCROLL TO BOTTOM AND CHECK FOR MORE ALERTS",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "job=~\"web-kollector\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Alerts Linux",
     "type": "table-old",
     "description": "MAKE SURE TO SCROLL TO BOTTOM AND CHECK FOR MORE ALERTS",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "job=~\"node_exporter.+\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "table"
      }
     ]
    },
    {
     "title": "Alerts observability",
     "type": "table-old",
     "description": "MAKE SURE TO SCROLL TO BOTTOM AND CHECK FOR MORE ALERTS",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "expr": "job=~\"observability-linux\"",
       "labelSelector": "*",
       "target": "Query",
       "type": "table"
      }
     ]
    }
   ]
  }
 ]
}