{
 "title": "VMware ESX Information - JAG",
 "description": "ESXI Host and VM information",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Host:",
    "query": "label_values(vmware_host_boot_timestamp_seconds,host_name)"
   },
   {
    "name": "vms",
    "query": "label_values({host_name=\"$hostname\"},vm_name)"
   }
  ]
 },
 "panels": [
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "vmware_host_cpu_usage{host_name=\"$hostname\"} / vmware_host_cpu_max{host_name=\"$hostname\"} * 100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "vmware_host_memory_usage{host_name=\"$hostname\"} / vmware_host_memory_max{host_name=\"$hostname\"} * 100"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - vmware_host_boot_timestamp_seconds{host_name=\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Host State",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "vmware_host_power_state{host_name=\"$hostname\"}"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "vms" },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 71 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 101 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 101 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 107 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 122 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 128 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 128 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 139 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 143 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 143 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 149 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 149 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 164 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 164 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 170 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 170 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 185 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 185 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 191 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 191 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 197 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 198 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 202 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 206 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 206 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 212 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 212 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 218 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 219 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 227 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 227 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 233 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 233 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 239 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 244 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 248 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 248 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 254 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 254 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  },
  { "title": "$vms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 260 } },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 261 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_power_state{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 261 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "nVCPU",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 261 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_num_cpu{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "VMWare Tools",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 261 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_guest_tools_running_status{vm_name=\"$vms\"}",
     "legendFormat": "{{tools_status}}"
    }
   ]
  },
  {
   "title": "Disk Usage %",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 261 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - vmware_vm_guest_disk_free{vm_name=\"$vms\"} /\nvmware_vm_guest_disk_capacity{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{partition}}"
    }
   ]
  },
  {
   "title": "Host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "vmware_vm_boot_timestamp_seconds{vm_name=\"$vms\"}",
     "legendFormat": "{{host_name}}"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_memory_max{vm_name=\"$vms\"}",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 265 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vmware_vm_mem_usage_average{vm_name=\"$vms\"} /\nvmware_vm_memory_max{vm_name=\"$vms\"} * 100",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 269 },
   "yaxes": [
    { "format": "rothz" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_usagemhz_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Disk Read x Write",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 269 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_disk_read_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    },
    {
     "expr": "vmware_vm_disk_write_average{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "CPU Ready",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 275 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_cpu_ready_summation{vm_name=\"$vms\"} ",
     "legendFormat": "{{vm_name}}"
    }
   ]
  },
  {
   "title": "Network In/Out",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 275 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "expr": "vmware_vm_net_transmitted_average{vm_name=\"$vms\"}",
     "legendFormat": "Out"
    },
    {
     "expr": "vmware_vm_net_received_average{vm_name=\"$vms\"}",
     "legendFormat": "In"
    }
   ]
  }
 ]
}