{
 "title": "VM Analytical - Windows Exporter - JAG",
 "description": "Basic overview of windows host metrics, based on WMI Exporter (v0.7.0)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Datacenter", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": "label_values(wmi_os_time, job)" },
   {
    "name": "host",
    "label": "Hostname",
    "query": "label_values(wmi_os_time{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "CPU Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Load | $host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "repeat": "host",
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "sum by (mode) (irate(wmi_cpu_time_total{instance=~\"$host\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System Exceptions | $host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_system_exception_dispatches_total{instance=~\"$host\"}[5m])",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "System Threads | $host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "wmi_system_threads{instance=~\"$host\"}",
     "legendFormat": "threads"
    }
   ]
  },
  { "title": "Memory Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Memory | $host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "RAM" }
   ],
   "targets": [
    {
     "expr": "wmi_os_virtual_memory_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Virtual"
    },
    {
     "expr": "wmi_cs_physical_memory_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Physical"
    },
    {
     "expr": "wmi_os_physical_memory_free_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Network Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Network Traffic | $host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_net_bytes_received_total{instance=~\"$host\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m]) > 0",
     "legendFormat": "Received"
    },
    {
     "expr": "- irate(wmi_net_bytes_sent_total{instance=~\"$host\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m]) < 0",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Network discarded/error | $host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "repeat": "host",
   "yaxes": [
    { "format": "pps", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "irate(wmi_net_packets_outbound_discarded{instance=~\"$host\",nic!~\"isatap.+\"}[5m]) + irate(wmi_net_packets_outbound_errors{instance=~\"$host\"}[5m])",
     "legendFormat": "Sent ({{nic}})"
    },
    {
     "expr": "irate(wmi_net_packets_received_discarded{instance=~\"$host\", nic!~\"isatap.+\"}[5m]) + irate(wmi_net_packets_received_errors{instance=~\"$host\"}[5m])",
     "legendFormat": "Received ({{nic}})"
    }
   ]
  },
  {
   "title": "Disk Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk (Free) | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "wmi_logical_disk_free_bytes{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Disk Activity | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(wmi_logical_disk_write_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(wmi_logical_disk_read_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    },
    {
     "title": "Disk IO | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(wmi_logical_disk_write_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(wmi_logical_disk_read_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    },
    {
     "title": "Disk (Free) | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "wmi_logical_disk_free_bytes{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Disk Activity | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(wmi_logical_disk_write_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(wmi_logical_disk_read_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    },
    {
     "title": "Disk IO | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(wmi_logical_disk_write_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(wmi_logical_disk_read_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    },
    {
     "title": "Disk (Free) | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "wmi_logical_disk_free_bytes{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Disk Activity | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(wmi_logical_disk_write_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(wmi_logical_disk_read_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    },
    {
     "title": "Disk IO | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(wmi_logical_disk_write_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(wmi_logical_disk_read_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    },
    {
     "title": "Disk (Free) | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "wmi_logical_disk_free_bytes{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Disk Activity | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(wmi_logical_disk_write_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(wmi_logical_disk_read_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    },
    {
     "title": "Disk IO | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(wmi_logical_disk_write_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(wmi_logical_disk_read_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    }
   ]
  }
 ]
}